### PR TITLE
Tsz hin

### PR DESCRIPTION
**Pull request by TszHin0**
I want to merge my UI Change into master.
I change the main, sign up, and sign in UI to look like the Marcus's design.

### CODE REVIEW

**Comment by Hanasou** [comment]
Hey, post some screenshots of the application here or on slack. Thanks.

**Comment by TszHin0** [comment]
image
image
image
image
(The last screen have no activaty, so you can't see it when you run the app)

**Comment by Hanasou** [comment]
Nice work. I'm going to test this later today to make sure these UI changes haven't gotten in the way of the functions. The last image should correspond to the DepartmentRegistrationActivity class. College selection should probably be a drop down menu (Spinner) instead.

FYI for anyone else, once a new branch merges into master, you'll have to rebase to make sure the branch you're working on is clean.

**Comment by Hanasou** [comment]
@TszHin0 Hey good work. Do you plan on also implementing the same style for the Faculty UI as well?

**Comment by TszHin0** [comment]
I am helping Dylan to finish the forum.Dylan said he would do the xml part. I will take a look after I finish the forum.

**Pull request merged**
